import { MarketStory } from "../types/marketplace";

export const fakestories: MarketStory[] = [
    {
        id: 1,
        title: "The Lost Kingdom",
        author: "John Doe",
        author_id: "user-1",
        content: "",
        ai_summary: "A thrilling adventure in a lost kingdom.",
        ai_genres: ["Fantasy", "Adventure"],
        average_rating: 4.5,
        rating_count: 100,
        total_downloads: 5000,
        total_donated_credits: 100,
        published_at: "2023-01-01",
        is_staff_pick: true,
        user_rating: 5
    },
    {
        id: 2,
        title: "Mystery of the Ancient Ruins",
        author: "Jane Smith",
        author_id: "user-2",
        content: "",
        ai_summary: "A captivating mystery set in ancient ruins.",
        ai_genres: ["Mystery", "Adventure"],
        average_rating: 4.7,
        rating_count: 80,
        total_downloads: 3000,
        total_donated_credits: 50,
        published_at: "2023-02-15",
        is_staff_pick: false,
        user_rating: 4
    },
{
    "id": 3,
    "title": "Echoes of the Forgotten Gods",
    "author": "Robert Williams",
    "author_id": "user-3",
    "content": "",
    "ai_summary": "An epic tale of gods and mortals battling for dominion.",
    "ai_genres": ["Fantasy", "Mythology"],
    "average_rating": 4.6,
    "rating_count": 95,
    "total_downloads": 4200,
    "total_donated_credits": 75,
    "published_at": "2023-03-20",
    "is_staff_pick": true,
    "user_rating": 4.8
  },
  {
    "id": 4,
    "title": "The Last Star Navigator",
    "author": "Emily Carter",
    "author_id": "user-4",
    "content": "",
    "ai_summary": "A lone navigator races against time to save a dying galaxy.",
    "ai_genres": ["Science Fiction", "Adventure"],
    "average_rating": 4.3,
    "rating_count": 60,
    "total_downloads": 2500,
    "total_donated_credits": 25,
    "published_at": "2023-04-10",
    "is_staff_pick": false,
    "user_rating": 3.9
  },
  {
    "id": 5,
    "title": "Crimson Shadows of Blackwood Manor",
    "author": "David Brown",
    "author_id": "user-5",
    "content": "",
    "ai_summary": "A chilling gothic horror story set in a haunted manor.",
    "ai_genres": ["Horror", "Mystery"],
    "average_rating": 4.8,
    "rating_count": 120,
    "total_downloads": 6500,
    "total_donated_credits": 120,
    "published_at": "2023-05-05",
    "is_staff_pick": true,
    "user_rating": 5
  },
  {
    "id": 6,
    "title": "The Clockwork Heart Thief",
    "author": "Sarah Johnson",
    "author_id": "user-6",
    "content": "",
    "ai_summary": "A steampunk adventure about a thief with a mechanical heart.",
    "ai_genres": ["Steampunk", "Adventure"],
    "average_rating": 4.2,
    "rating_count": 70,
    "total_downloads": 3800,
    "total_donated_credits": 60,
    "published_at": "2023-06-18",
    "is_staff_pick": false,
    "user_rating": 4.0
  },
  {
    "id": 7,
    "title": "Beneath the Serpent's Scale",
    "author": "Michael Green",
    "author_id": "user-7",
    "content": "",
    "ai_summary": "An archaeologist uncovers a hidden city beneath an ancient volcano.",
    "ai_genres": ["Adventure", "Archaeology"],
    "average_rating": 4.5,
    "rating_count": 110,
    "total_downloads": 5800,
    "total_donated_credits": 110,
    "published_at": "2023-07-01",
    "is_staff_pick": true,
    "user_rating": 4.9
  },
  {
    "id": 8,
    "title": "The Silent Witness",
    "author": "Jessica Adams",
    "author_id": "user-8",
    "content": "",
    "ai_summary": "A detective investigates a murder with no witnesses.",
    "ai_genres": ["Mystery", "Crime"],
    "average_rating": 4.1,
    "rating_count": 55,
    "total_downloads": 2800,
    "total_donated_credits": 35,
    "published_at": "2023-08-12",
    "is_staff_pick": false,
    "user_rating": 3.7
  },
  {
    "id": 9,
    "title": "Echoes in the Void",
    "author": "Kevin Hill",
    "author_id": "user-9",
    "content": "",
    "ai_summary": "A psychological thriller exploring isolation and paranoia.",
    "ai_genres": ["Thriller", "Psychological"],
    "average_rating": 4.7,
    "rating_count": 105,
    "total_downloads": 5200,
    "total_donated_credits": 90,
    "published_at": "2023-09-08",
    "is_staff_pick": true,
    "user_rating": 4.8
  },
  {
    "id": 10,
    "title": "The Last Dragon Rider",
    "author": "Ashley White",
    "author_id": "user-10",
    "content": "",
    "ai_summary": "A young warrior trains to become the last dragon rider.",
    "ai_genres": ["Fantasy", "Adventure"],
    "average_rating": 4.4,
    "rating_count": 85,
    "total_downloads": 4000,
    "total_donated_credits": 65,
    "published_at": "2023-10-22",
    "is_staff_pick": false,
    "user_rating": 4.2
  },
  {
    "id": 11,
    "title": "The Quantum Enigma",
    "author": "Brian Taylor",
    "author_id": "user-11",
    "content": "",
    "ai_summary": "A scientist unravels the mysteries of quantum physics.",
    "ai_genres": ["Science Fiction", "Thriller"],
    "average_rating": 4.6,
    "rating_count": 90,
    "total_downloads": 4500,
    "total_donated_credits": 80,
    "published_at": "2023-11-05",
    "is_staff_pick": true,
    "user_rating": 4.7
  },
  {
    "id": 12,
    "title": "The Shadow Broker's Deal",
    "author": "Nicole King",
    "author_id": "user-12",
    "content": "",
    "ai_summary": "A dangerous deal with a shadowy figure changes everything.",
    "ai_genres": ["Thriller", "Crime"],
    "average_rating": 4.3,
    "rating_count": 75,
    "total_downloads": 3600,
    "total_donated_credits": 55,
    "published_at": "2023-12-01",
    "is_staff_pick": false,
    "user_rating": 4.1
  },
  {
    "id": 13,
    "title": "Beneath a Crimson Sky",
    "author": "Adam Clark",
    "author_id": "user-13",
    "content": "",
    "ai_summary": "A war story about survival and sacrifice on a ravaged planet.",
    "ai_genres": ["Science Fiction", "War"],
    "average_rating": 4.8,
    "rating_count": 115,
    "total_downloads": 6200,
    "total_donated_credits": 130,
    "published_at": "2024-01-15",
    "is_staff_pick": true,
    "user_rating": 5.0
  },
  {
    "id": 14,
    "title": "The Alchemist’s Secret",
    "author": "Olivia Brown",
    "author_id": "user-14",
    "content": "",
    "ai_summary": "An alchemist searches for the ultimate elixir.",
    "ai_genres": ["Fantasy", "Mystery"],
    "average_rating": 4.2,
    "rating_count": 68,
    "total_downloads": 3400,
    "total_donated_credits": 50,
    "published_at": "2024-02-29",
    "is_staff_pick": false,
    "user_rating": 3.8
  },
  {
    "id": 15,
    "title": "Echoes of the Deep",
    "author": "Ethan Smith",
    "author_id": "user-15",
    "content": "",
    "ai_summary": "A deep-sea explorer discovers a lost civilization.",
    "ai_genres": ["Adventure", "Science Fiction"],
    "average_rating": 4.7,
    "rating_count": 102,
    "total_downloads": 5500,
    "total_donated_credits": 98,
    "published_at": "2024-03-18",
    "is_staff_pick": true,
    "user_rating": 4.9
  },
  {
    "id": 16,
    "title": "The Last Librarian",
    "author": "Chloe Davis",
    "author_id": "user-16",
    "content": "",
    "ai_summary": "In a world without books, a librarian fights to preserve knowledge.",
    "ai_genres": ["Fantasy", "Dystopian"],
    "average_rating": 4.0,
    "rating_count": 58,
    "total_downloads": 2700,
    "total_donated_credits": 30,
    "published_at": "2024-04-05",
    "is_staff_pick": false,
    "user_rating": 3.6
  },
  {
    "id": 17,
    "title": "The Serpent’s Curse",
    "author": "Ryan Miller",
    "author_id": "user-17",
    "content": "",
    "ai_summary": "A family is haunted by a generations-old curse.",
    "ai_genres": ["Horror", "Mystery"],
    "average_rating": 4.6,
    "rating_count": 98,
    "total_downloads": 5000,
    "total_donated_credits": 92,
    "published_at": "2024-05-23",
    "is_staff_pick": true,
    "user_rating": 4.8
  },
  {
    "id": 18,
    "title": "The Stolen Memory",
    "author": "Mia Jones",
    "author_id": "user-18",
    "content": "",
    "ai_summary": "A man wakes up with no memory of his past.",
    "ai_genres": ["Thriller", "Mystery"],
    "average_rating": 4.3,
    "rating_count": 72,
    "total_downloads": 3900,
    "total_donated_credits": 62,
    "published_at": "2024-06-11",
    "is_staff_pick": false,
    "user_rating": 4.0
  },
  {
    "id": 19,
    "title": "Beyond the Crimson Horizon",
    "author": "Lucas Green",
    "author_id": "user-19",
    "content": "",
    "ai_summary": "A crew explores a newly discovered planet.",
    "ai_genres": ["Science Fiction", "Adventure"],
    "average_rating": 4.5,
    "rating_count": 88,
    "total_downloads": 4300,
    "total_donated_credits": 78,
    "published_at": "2024-07-08",
    "is_staff_pick": true,
    "user_rating": 4.7
  },
  {
    "id": 20,
    "title": "The Clockmaker’s Daughter",
    "author": "Ava Black",
    "author_id": "user-20",
    "content": "",
    "ai_summary": "A young woman inherits a mysterious clockmaking business.",
    "ai_genres": ["Mystery", "Romance"],
    "average_rating": 4.1,
    "rating_count": 65,
    "total_downloads": 3200,
    "total_donated_credits": 48,
    "published_at": "2024-08-15",
    "is_staff_pick": false,
    "user_rating": 3.9
  }
]